language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "VFT+c0k8z2tvUQjQNy13LiwCCxCepI4KzyuP8+Fe5XN2QXBAYDITbLOCzVDCbyBIcEC5+mD4XhHO+yxafaDofPgizOA0oXS8KLyo4VmwCgMcL4jLwz29qdsdBd5yheExCRUm3aFDFL+kNGJMbxAFlMBYrwd/Qrdq2vrOhKX0O0JICzPfv6iPYw9dPB24HJ7InAxAkIHwXy4NDaUCkRhnRGTqodXp/0sZWlBRRc6JDDkg0SSzEidLYywUqjx0byXjb6dBPh+j3Nfqn7g5+l8Shgag38ri+jGppTIfyXqVfzfIxbo4cuoNooy6Y2R2UHXauFnDvOylQ6ysqOUWblaA1LPbuAkqKh37CNh60TJsVHIYUpKsEL5EqOPGp3yOk2qOYS59McMP3GcXUrqB8TYixj6kW6r75grn+dPYZgKkW3Wcx7oEU9UVNJNyqXT2r+eH2FMT1sokjRJz0qW/k69By96GZDVVR8JwyGIL/9+YtxxOBhfRSvWG2+cQtuFLqoq2v22gD7IAh8NX7WdczU+EDxHb+HvgE/mWBz/mkdWu7vZ4NGp5Q2RJDBWZNN9v9T+CNzgpn/tSbWg12WNfH6rXoxVDflRStkbdjC8KvSwh4lASg2f3Bfb8YLZDhSjo9ahi5hBxjPNmDofQsWfCgh16V/IGwhDIhrmoW0lZ7RpVH1s="
  api_key: # b31b
    secure: "g2yWQCY3fV3UtEU7azHEBlwdU6r9sk0d1aGFZ7wq2zpEn5CsqnNNiVwNgzEH90A+D7pPq9vkIX1YQWN4HqvllASSLgoCyBSG82BEk00mHUzkuOnmv7bW4/1caqx7TZmeoDMl6FwK/AFp7kK4/j431vCHAxK2cNZz/RHRlNlW5x0gHdubzIZrUFAyipg7zfw/tRoxlh+Psse+tiA1dnDxP9n5rSLLKz8J7qR7N4Uolh9G0sPK258w9dpWEYk4yI0GbYOOLwhmNCklRndN9kVrn5cfWrErW1oiEAO56mDnmz/vnWkfulC/ncHUVYW8AY/7YImRLghGpyMsPXStNXarZi7rvxA87gLdK6N1y/uWnNMeF2I6CoNEjpdYPmiihGoaW7Nn+FeG71HHg9vGNv98YlFdtL+9qerKsHZZpxbtJr2C1t727wU+j0NfGNj7s7QdWdMC9Xa93y96KO5ld88cp90ntO+HfF4ZWkHrlTPE1M1ojcoIDli9pQQefIKoqrELWH9701SXDQ3ilbZiPzERuc2/4ZtDmH71UD3JhSUs6FCA9V6oTB+AfOgR56R8bbRGlndks6Fx30MKPk0DMwnr6rtw3Bp+v5qehtmKSDMGbwG5Q1aDmQNliPQXxdfJTE3LFNadLBG9g6NSXMCOL8m9RyIYWFtYARgMklQsy5LPhN4="
  on:
    tags: true
    node: lts/*
